[package]
name = "lovesay"
version = "0.5.4"
edition = "2021"
description = "lovesay but rusty"
repository = "https://github.com/dotzenith/lovesay.rs"
license = "MIT"

[dependencies]
shellexpand = "3.0"
chrono = "0.4.26"
textwrap = "0.16.0"
term_size = "0.3.2"
atty = "0.2.14"
kolorz = "0.6.0"
